version: '3'

networks:
  scrapper-network:
    driver: bridge

services:
  scrapper-python:
    image: scrapper-python
    build:
      context: ./python
    container_name: scrapper-python
    working_dir: /src
    volumes:
      - ../src:/src
      - ../results:/src/results
    tty: true
    networks:
      - scrapper-network

  selenium-server:
    image: selenium-server
    build:
      context: ./selenium-server
    container_name: selenium-server
    volumes_from:
      - scrapper-python
    networks:
      - scrapper-network
